version: '3.8'

services:
  contactCustomer:
    build:
      context: ./ContactCustomer
      dockerfile: Dockerfile.contact
    container_name: ContactCentre
    ports:
      - "3000:3000"
    depends_on:
      - server

  Policies:
    build:
      context: ./Policies
      dockerfile: Dockerfile.policy
    container_name: PolicyCentre
    ports:
      - "3001:3001"
    depends_on:
      - server

  Claims:
    build:
      context: ./Claims
      dockerfile: Dockerfile.claim
    container_name: ClaimsCentre
    ports:
      - "3002:3002"
    depends_on:
      - server

  Billing:
    build:
      context: ./Billing
      dockerfile: Dockerfile.billing
    container_name: BillingCentre
    ports:
      - "3003:3003"
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://10.192.190.148:27017/registeredUser
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
