version: '3.8'

services:
  contactcentre:
    build:
      context: ./ContactCustomer
      dockerfile: Dockerfile.contact
    container_name: contactcentre
    ports:
      - "3000:3000"
    depends_on:
      - server

  policiescentre:
    build:
      context: ./Policies
      dockerfile: Dockerfile.policy
    container_name: policycentre
    ports:
      - "3001:3001"
    depends_on:
      - server

  claimscentre:
    build:
      context: ./Claims
      dockerfile: Dockerfile.claim
    container_name: claimscentre
    ports:
      - "3003:3003"
    depends_on:
      - server

  billingcentre:
    build:
      context: ./billing
      dockerfile: Dockerfile.billing
    container_name: billingcentre
    ports:
      - "3002:3002"
    depends_on:
      - server

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://10.192.190.148:27017/registeredUser
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
